package com.woniu.mapper;

import com.woniu.pojo.Rolepermission;
import com.woniu.pojo.RolepermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolepermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    long countByExample(RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int deleteByExample(RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer rpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int insert(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int insertSelective(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    List<Rolepermission> selectByExample(RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    Rolepermission selectByPrimaryKey(Integer rpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Rolepermission record, @Param("example") RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Rolepermission record, @Param("example") RolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByPrimaryKey(Rolepermission record);
}