package com.woniu.mapper;

import com.woniu.pojo.Useres;
import com.woniu.pojo.UseresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UseresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    long countByExample(UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int deleteByExample(UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int insert(Useres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int insertSelective(Useres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    List<Useres> selectByExample(UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    Useres selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Useres record, @Param("example") UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Useres record, @Param("example") UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Useres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useres
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    int updateByPrimaryKey(Useres record);
}