package com.woniu.pojo;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.rid
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.rname
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private String rname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.rid
     *
     * @return the value of roles.rid
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.rid
     *
     * @param rid the value for roles.rid
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.rname
     *
     * @return the value of roles.rname
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.rname
     *
     * @param rname the value for roles.rname
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setRname(String rname) {
        this.rname = rname;
    }
}