package com.woniu.pojo;

public class Useres {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useres.uid
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useres.uname
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useres.upwd
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useres.uaccount
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private String uaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useres.ueamail
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    private String ueamail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useres.uid
     *
     * @return the value of useres.uid
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useres.uid
     *
     * @param uid the value for useres.uid
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useres.uname
     *
     * @return the value of useres.uname
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useres.uname
     *
     * @param uname the value for useres.uname
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useres.upwd
     *
     * @return the value of useres.upwd
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useres.upwd
     *
     * @param upwd the value for useres.upwd
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useres.uaccount
     *
     * @return the value of useres.uaccount
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public String getUaccount() {
        return uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useres.uaccount
     *
     * @param uaccount the value for useres.uaccount
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setUaccount(String uaccount) {
        this.uaccount = uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useres.ueamail
     *
     * @return the value of useres.ueamail
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public String getUeamail() {
        return ueamail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useres.ueamail
     *
     * @param ueamail the value for useres.ueamail
     *
     * @mbg.generated Mon Jun 08 19:20:02 GMT+08:00 2020
     */
    public void setUeamail(String ueamail) {
        this.ueamail = ueamail;
    }
}